export const spainProvinces = [
    'Almería',
    'Cádiz',
    'Córdoba',
    'Granada',
    'Huelva',
    'Jaén',
    'Málaga',
    'Sevilla',
    'Huesca',
    'Teruel',
    'Zaragoza',
    'Asturias',
    'Islas Baleares',
    'Las Palmas',
    'Santa Cruz de Tenerife',
    'Cantabria',
    'Ávila',
    'Burgos',
    'León',
    'Palencia',
    'Salamanca',
    'Segovia',
    'Soria',
    'Valladolid',
    'Zamora',
    'Albacete',
    'Ciudad Real',
    'Cuenca',
    'Guadalajara',
    'Toledo',
    'Barcelona',
    'Gerona',
    'Lérida',
    'Tarragona',
    'Badajoz',
    'Cáceres',
    'La Coruña',
    'Lugo',
    'Orense',
    'Pontevedra',
    'Madrid',
    'Murcia',
    'Navarra',
    'La Rioja',
    'Álava',
    'Guipúzcoa',
    'Vizcaya',
    'Alicante',
    'Castellón',
    'Valencia',
];
