export const spainRegions = [
    'Andalucía',
    'Aragón',
    'Asturias',
    'Islas Baleares',
    'Canarias',
    'Cantabria',
    'Castilla y León',
    'Castilla-La Mancha',
    'Cataluña',
    'Extremadura',
    'Galicia',
    'Madrid',
    'Murcia',
    'Navarra',
    'La Rioja',
    'País Vasco',
    'Comunidad Valenciana',
];

export const spainProvinces: Record<string, string[]> = {
    Andalucía: [
        'Almería',
        'Cádiz',
        'Córdoba',
        'Granada',
        'Huelva',
        'Jaén',
        'Málaga',
        'Sevilla',
    ],
    Aragón: ['Huesca', 'Teruel', 'Zaragoza'],
    Asturias: ['Asturias'],
    'Islas Baleares': ['Islas Baleares'],
    Canarias: ['Las Palmas', 'Santa Cruz de Tenerife'],
    Cantabria: ['Cantabria'],
    'Castilla y León': [
        'Ávila',
        'Burgos',
        'León',
        'Palencia',
        'Salamanca',
        'Segovia',
        'Soria',
        'Valladolid',
        'Zamora',
    ],
    'Castilla-La Mancha': [
        'Albacete',
        'Ciudad Real',
        'Cuenca',
        'Guadalajara',
        'Toledo',
    ],
    Cataluña: ['Barcelona', 'Gerona', 'Lérida', 'Tarragona'],
    Extremadura: ['Badajoz', 'Cáceres'],
    Galicia: ['La Coruña', 'Lugo', 'Orense', 'Pontevedra'],
    Madrid: ['Madrid'],
    Murcia: ['Murcia'],
    Navarra: ['Navarra'],
    'La Rioja': ['La Rioja'],
    'País Vasco': ['Álava', 'Guipúzcoa', 'Vizcaya'],
    'Comunidad Valenciana': ['Alicante', 'Castellón', 'Valencia'],
};
